config/routes.rb
PropertyCertifyCoUk::Application.routes.draw do

  get "about", to: 'welcome#about'
  get "residential", to: 'welcome#residential'
  get "testimonial", to: 'welcome#testimonial'
  get "contact", to: "welcome#contact"
  get "commercial", to: "welcome#commercial"
  post "property_info", to: "welcome#property_info"
  post "enquiry_info", to: "welcome#enquiry_info"

  root 'welcome#index'

end

app/models/contact.rb
class Contact < ActiveRecord::Base
	validates_presence_of :when, :address, :name, :email, :phone_number

	ALL_HOURS = ["8 to 10am","10am to 12pm","12pm to 2pm","2pm to 4pm","4pm to 6pm","6pm to 8pm","8pm to 10pm","10pm to 12pm","12pm to 2am","2am to 4am","4am to 6am","6am to 8am"]
  HOUR_NAMES = ALL_HOURS.each_with_index.map{|x,n|[x,n]}
end

app/models/enquiry.rb
class Enquiry < ActiveRecord::Base
	validates_presence_of  :name, :email, :telephone, :enquiry
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
  end

  def about
  end

  def residential
    @contact = Contact.new
  end

  def testimonial
  end

  def contact
    @enquiry = Enquiry.new
  end

  def commercial
  end

  def property_info
    @contact = Contact.new(contact_params)
    if @contact.save
      WelcomeMailer.registration_confirmation(@contact).deliver
      flash[:notice] = "An Email has been sent, We will contact u soon"
    else
      flash[:error] = "Please Fill required fields."
    end
    redirect_to :back
  end

  def enquiry_info
    @enquiry = Enquiry.new(enquiry_params)
    if @enquiry.save
      EnquiryMailer.enquiry_confirmation(@enquiry).deliver
      flash[:notice] = "An Email has been sent, We will contact u soon"
    else
      flash[:error] = "Please Fill required fields."
    end
    redirect_to :back
  end
end

private

  # Never trust parameters from the scary internet, only allow the white list through.
  def contact_params
    params.require(:contact).permit(:when, :time, :address,:name,:email, :phone_number)
  end

  def enquiry_params
    params.require(:enquiry).permit(:name, :telephone, :email, :enquiry)
  end

app/helpers/application_helper.rb
module ApplicationHelper
	def nav_link(link_text, link_path)
  	class_name = current_page?(link_path) ? 'active' : nil

  	content_tag(:li, :class => class_name) do
    	link_to link_text, link_path
  	end
	end

	def testimonial(text, name)
		class_name = cycle('pull-right', 'pull-left')
		content_tag(:blockquote, :class => class_name) do
			content_tag(:p, text) +
			content_tag(:small, name)
		end
	end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PropertyCertifyCoUk</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="shortcut icon" href="../../docs-assets/ico/favicon.png">

    <title>Static Top Navbar Example for Bootstrap</title>

    <!-- Bootstrap core CSS -->
    <link href="../../dist/css/bootstrap.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="navbar-static-top.css" rel="stylesheet">

    <!-- Just for debugging purposes. Don't actually copy this line! -->
    <!--[if lt IE 9]><script src="../../docs-assets/js/ie8-responsive-file-warning.js"></script><![endif]-->

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
    <![endif]-->
</head>
<body>
  <!-- Static navbar -->
  <div class="navbar navbar-default navbar-static-top" role="navigation">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="#">Property Certify</a>
      </div>
      <div class="navbar-collapse collapse">
        <ul class="nav navbar-nav">
          <li><%= nav_link('Home', root_path) %></li>
          <li><%= nav_link('About', about_path) %></li>
          <li><%= nav_link('Residential EPC', residential_path) %></li>
          <li><%= nav_link('Commercial EPC', commercial_path) %></li>
          <li><%= nav_link('Testimonial', testimonial_path) %>
          <li><%= nav_link('Contact Us', contact_path) %></li>
          <!-- <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Dropdown <b class="caret"></b></a>
            <ul class="dropdown-menu">
              <li><a href="#">Action</a></li>
              <li><a href="#">Another action</a></li>
              <li><a href="#">Something else here</a></li>
              <li class="divider"></li>
              <li class="dropdown-header">Nav header</li>
              <li><a href="#">Separated link</a></li>
              <li><a href="#">One more separated link</a></li>
            </ul>
          </li> -->
        <!-- </ul>
        <ul class="nav navbar-nav navbar-right">
          <li><a href="../navbar/">Default</a></li>
          <li class="active"><a href="./">Static top</a></li>
          <li><a href="../navbar-fixed-top/">Fixed top</a></li>
        </ul> -->
      </div><!--/.nav-collapse -->
    </div>
  </div>


  <div class="container">

    <!-- Main component for a primary marketing message or call to action -->
    <!-- <div class="jumbotron"> -->
      <!-- <h1>Navbar example</h1>
      <p>This example is a quick exercise to illustrate how the default, static and fixed to top navbar work. It includes the responsive CSS and HTML, so it also adapts to your viewport and device.</p>
      <p>To see the difference between static and fixed top navbars, just scroll.</p>
      <p>
        <a class="btn btn-lg btn-primary" href="../../components/#navbar" role="button">View navbar docs &raquo;</a>
      </p> -->
    <!-- </div> -->

    <%= yield %>

    <hr>
    
    <footer>
      <p>&copy; PropertyCertify.CO.UK 2014</p>
    </footer>
  </div> <!-- /container -->

  <!-- Bootstrap core JavaScript
  ================================================== -->
  <!-- Placed at the end of the document so the pages load faster -->
  <script src="https://code.jquery.com/jquery-1.10.2.min.js"></script>
  <script src="../../dist/js/bootstrap.min.js"></script>

</body>
</html>

app/views/shared/_flash_messages.html.erb
<div id="flash_messages">
  <% flash.each do |key, value| %>
    <% if () %>
      <% success_class = "alert-success" %>
    <% else %>
      <% error_class = "alert-error" %>
    <% end %>
    <div class="alert alert-success alert-dismissable" >
      <a class="close" data-dismiss="alert" href="#">×
      </a>
      <i class="icon-ok-sign"></i>
      <%= value %>
    </div>
  <% end %>
</div>

app/views/welcome/about.html.erb
<div class="page-header text-center">
  <h1>About Property Certify <small>We are South London's leading property survey experts.</small></h1>
</div>
<p class="lead text-center">Property Certify is a dedicated Energy Performance Certificate provider set up to meet the increasing demand for Energy Performance Certificates to property professionals, businesses and home owners.

Based in Kent, we are able to deliver all our services to London and the South East.

We work closely with major estate agent chains, solicitors and chartered surveyors and can therefore offer a full range of survey work.</p>
<div class="row">
  <div class="col-lg-4">
    <h2>About Energy Performance Certificates</h3>
    <p>In May 2010, the UK Government dropped the requirement for Home Information Packs (Hips) for residents in England and Wales. In their place they introduced the Energy Performance Certificate (EPC) which became mandatory for all households, and business properties.</p>
    <p class='text-danger'>You cannot sell or rent a property in England or Wales without an Energy Performance Certificate (EPC), for penalty is a fine upto £5000.</p>
    <p><a class="btn btn-success" href="#" role="button">Book Now &raquo;</a></p>
  </div>
  <div class="col-lg-4">
    <h2>The Idea behind Energy Performance Certificates (EPC)</h3>
    <p>Buildings are almost responsible for 50% of the UK's energy consumption, which is twice that of cars and planes.</p>
    <p>Energy Performance Certificates have been adopted to bring about greater awareness of energy efficiency and what we can do reduce carbon emissions. This has evolved from the Government's acceptance of the 'Kyoto Agreement' and the EU's ' Energy Performance of Buildings Directive'.</p>
  </div>
  <div class="col-lg-4">
    <h2>Do I need an Energy Performance Certificate (EPC)</h3>
    <p>YES... If you wish to sell or let any residential or commercial property then you will need an EPC.</p>
		<p>YES... When a new building is constructed then no later than 5 days after construction.</p>
		<p>NO... Some buildings do not require an EPC. Contact us for more information if required.</p>
  </div>
</div>

app/views/welcome/commercial.html.erb
<div class="row">
  <div class="col-lg-12">
		<div class="page-header text-center">
		  <h1>Free Commercial EPC</h1>
		  <p>Because of the unique way our company in structured we are able to offer free Energy Performance certificate quotes to businesses in the following areas: Bexley, Bromley, Croydon, Greenwich, Lambeth, Lewisham and Southwark.</p>
		  <span class="text-small">(If your company is outside of these areas, we may still be able to offer you a free quote, please call for info and advice)</span>
		</div>
	</div>
</div>
<div class="row">
  <div class="col-lg-12">
		<h1>Book your EPC Survey now using the form below</h1>
		<p>OUR PROMISE TO YOU</p>
		<ul>
  		<li>Our fees are inclusive of VAT</li>
  		<li>Your details will never be passed to 3rd parties</li>
  		<li>You will receive a confirmation by SMS</li>
  		<li>Our experienced Government Accredited Energy Assessors will always show you ID</li>
  	</ul>
  	<span class="text-small"> We only use this information to process the quote. 
  		Your information is not sent to third parties</span>
	</div>
</div>

app/views/welcome/contact.html.erb
<%= simple_form_for(@enquiry, :url => "/enquiry_info", :method => "post") do |f| %>
  <%= render 'shared/flash_messages' if !flash.empty? %>
  <% if @enquiry.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@contact.errors.count, "error") %> prohibited this applicant from being saved:</h2>

      <ul>
      <% @enquiry.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="row">
    <div class="col-sm-12">
      <div class="col-md-2"><%= f.label :name %></div>
      <div class="col-md-10">
        <%= f.text_field(:name) %>
      </div>
    </div>
  </div>
  <br/>
  <div class="row">
    <div class="col-sm-12">
      <div class="col-md-2"><%= f.label :telephone %></div>
      <div class="col-md-10">
        <%= f.text_field(:telephone) %>
      </div>
    </div>
  </div>
  <br/>
  <div class="row">
    <div class="col-sm-12">
      <div class="col-md-2"><%= f.label :email %></div>
      <div class="col-md-10">
        <%= f.text_field(:email) %>
      </div>
    </div>
  </div>
  <br/>
  <div class="row">
    <div class="col-sm-12">
      <div class="col-md-2"><%= f.label :enquiry %></div>
      <div class="col-md-10">
        <%= f.text_area(:enquiry) %>
      </div>
    </div>
  </div>
  <br/><br/>
  <div style="background-color: black; margin-left: 0px; margin-right: 0px;" class="form-group">
    <div class="col-md-offset-2 col-sm-10">
      <%= f.submit  "Submit", :class => "btn btn-success" %>
    </div>
  </div>
<% end %>

app/views/welcome/index.html.erb
<%= link_to(image_tag("banner.jpg", class: "img-responsive center-block"), residential_path) %>
<!-- Example row of columns -->
<div class="row featurette">
  <div class="col-md-12">
    <h2 class="featurette-heading text-center">Cheapest Energy Performance Certificates in South London.</h2>
    <p class="lead text-center">Welcome to Property Certify, we are property survey experts specialising in providing the cheapest Energy Certificates in Bexley, Bromley, Croydon, Greenwich, Lambeth, Lewisham Southwark and Wandsworth.
		</p>
		<p class="text-center"><span class="text-muted">(If your company is outside of these areas, we may still be able to offer you a free survey, please call for info and advice)
		<span></p>
  </div>
</div>
<hr class="featurette-divider">
<div class="row">
  <div class="col-md-6">
    <h2>What are Energy Performance Certificates?</h2>
    <p>Energy Performance Certificates also known as EPCs show how energy efficient a property is. The certificate will provide a rating of the energy efficiency and CO2 emissions of a property from A grade the highest to grade G being very inefficient. </p>
    <p> <%= link_to 'Book Now', residential_path, class: "btn btn-success" %></p>
 </div>
  <div class="col-md-6">
    <h2>Who needs an EPC?</h2>
    <p>All buildings in the UK whether residential or commercial that are constructed, sold or rented out will need to have an Energy Performance Certificate.</p>
    <p> <%= link_to 'Book Now', residential_path, class: "btn btn-success" %></p>
  </div>
</div>
<hr class="featurette-divider">
<div class="row">
	<div class="col-md-4">
		<div class="panel panel-success">
			<h3 class="panel-heading panel-title">Inner London</h3>
			<h2 class="text-center">Only &#163;35 Inclusive</h2>
		</div>
	</div>
	<div class="col-md-4">
		<div class="panel panel-success">
			<h3 class="panel-heading panel-title">Outer London</h3>
			<h2 class="text-center">Only &#163;45 Inclusive</h2>
		</div>
	</div>
	<div class="col-md-4">
		<div class="panel panel-success">
			<h3 class="panel-heading panel-title">Commercial EPC Quotes</h3>
			<h2 class="text-center">Free!</h2>
		</div>
	</div>
</div>
<div class="row">
  <div class="col-md-6">
  	<h2>Our Fees</h2>
  	<p>We provide a fast and reliable service at the lowest rates.</p>
  	<h3>Our Promise to You</h3>
  	<ul>
  		<li>Our fees are inclusive of VAT</li>
  		<li>Your details will never be passed to 3rd parties</li>
  		<li>You will receive a confirmation by SMS</li>
  		<li>Our experienced Government Accredited Energy Assessors will always show you ID</li>
  	</ul>
  </div>
</div>

app/views/welcome/residential.html.erb
<div class="row">
  <div class="col-lg-12">
		<div class="page-header text-center">
		  <h1>Cheapest Residential Energy Performance Certificates in South London</h1>
		</div>
	</div>
</div>
<p class="lead text-center">PWelcome to Property Certify, we provide the cheapest Energy Performance Certificates for your home in the following areas Bexley, Bromley, Croydon, Greenwich, Lambeth, Lewisham and Southwark.</p>
<div class="row">
  <div class="col-lg-6">
    <h2>Our Fees</h3>
    <p class="text-muted">See why our Fees are the cheapest in South London</p>
    <ul>
    	<li>£35 for Bromley, Greenwich, Lambeth, Lewisham Southwark and Wandsworth</li>
    	<li>£45 for Bexley Croydon, Dartford, Gravesham and Sevenoaks</li>
    	<li>£55 for Ashford, Maidstone, Malling, Medway and Tonbridge</li>
    	<li>£60 for for express EPC (same day if ordered before 1pm</li>
    </ul>
  </div>
  <div class="col-lg-6">
    <h2>Book your EPC Survey now using the form below</h3>
    <p class="text-muted">OUR PROMISE TO YOU</p>
    <ul>
    	<li>Our fees are inclusive of VAT</li>
    	<li>Your details will never be passed to 3rd parties</li>
    	<li>You will receive a confirmation by SMS</li>
    	<li>Our experienced Government Accredited Energy Assessors will always show you ID</li>
    </ul>
  </div>
<div>
<div class="row">
  <div class="col-sm-12">
    <%= simple_form_for(@contact, :url => "/property_info", :method => "post") do |f| %>
    <%= render 'shared/flash_messages' if !flash.empty? %>
      <% if @contact.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@contact.errors.count, "error") %> prohibited this applicant from being saved:</h2>

          <ul>
          <% @contact.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
          </ul>
        </div>
      <% end %>
      <div class="row">
        <div class="col-sm-12">
          <div class="col-md-2"><%= f.label :when %></div>
          <div class="col-md-10">
            <%= f.text_field(:when) %>
          </div>
        </div>
      </div>
      <br/>
      <br/>
      <div class="form-group">
        <div class="row">
          <div class="col-sm-12">
            <label class="ss-q-title" for="time">Select Your Preferred Time</label>
            <div class="com-md-2"></div>
            <div class="col-md-10 col-md-offset-2">
              <div class="checkbox">
                <label>
                  <input type="checkbox" value="8am to 10am" name= "contact[time]">
                  8 to 10am
                </label>
              </div>
              <div class="checkbox">
                <label>
                  <input type="checkbox" value="10am to 12pm" name= "contact[time]">
                  10am to 12pm
                </label>
              </div>
              <div class="checkbox">
                <label>
                  <input type="checkbox"  value="12pm to 2pm" name= "contact[time]">
                  12pm to 2pm
                </label>
              </div>
              <div class="checkbox">
                <label>
                  <input type="checkbox" value="2pm to 4pm" name= "contact[time]">
                  2pm to 4pm
                </label>
              </div>
              <div class="checkbox">
                <label>
                  <input type="checkbox" value="12pm to 2pm" name= "contact[time]">
                  12pm to 2pm
                </label>
              </div>
              <div class="checkbox">
                <label>
                  <input type="checkbox" value="4pm to 6pm" name= "contact[time]">
                  4pm to 6pm
                </label>
              </div>
              <div class="checkbox">
                <label>
                  <input type="checkbox" value="12pm to 2pm" name= "contact[time]">
                  12pm to 2pm
                </label>
              </div>
              <div class="checkbox">
                <label>
                  <input type="checkbox" value="6pm to 8pm" name= "contact[time]">
                  6pm to 8pm
                </label>
              </div>
            </div>
          </div>
        </div>
      </div>
      <br/>
      <div class="row">
        <div class="col-sm-12">
          <div class="col-md-2"><%= f.label :address %></div>
          <div class="col-md-10"><%= f.text_area :address %></div>
        </div>
      </div>
      <br/>
      <div class="row">
        <div class="col-sm-12">
          <div class="col-md-2"><%= f.label :name %></div>
          <div class="col-md-10"><%= f.text_field :name %></div>
        </div>
      </div>
      <br/>
      <div class="row">
        <div class="col-sm-12">
          <div class="col-md-2"><%= f.label :email %></div>
          <div class="col-md-10"><%= f.text_field :email %></div>
        </div>
      </div>
      <br/>
      <div class="row">
        <div class="col-sm-12">
          <div class="col-md-2"><%= f.label :phone_number %></div>
          <div class="col-md-10"><%= f.text_field :phone_number %></div>
        </div>
      </div>
      <br/>
      <div style="background-color: black; margin-left: 0px; margin-right: 0px;" class="form-group">
        <div class="col-md-offset-2 col-sm-10">
          <%= f.submit  "Submit", :class => "btn btn-success" %>
        </div>
      </div>
    <% end %>
    <div class="col-md-offset-2 col-sm-10">
      <div class="password-warning">Never submit passwords through Google Forms.</div>
      <div class="ss-footer"><div class="ss-attribution"></div>
      <div class="ss-legal"><span class="ss-powered-by">Powered by <a href="http://docs.google.com">Google Docs</a></span>
      <span class="ss-terms"><small><a href="https://spreadsheets.google.com/spreadsheet/reportabuse?pli=1&amp;hl=en_GB&amp;bc=transparent&amp;f=Arial%252C%2BVerdana%252C%2Bsans-serif&amp;hl=en_GB&amp;htc=%2523666666&amp;key=0AsXMMvBKGqckdDJsend5cW94SkVQeFRtSWVFVWh2blE&amp;lc=%2523336699&amp;pli=1&amp;tc=%2523333333&amp;ttl=0&amp;source=https://spreadsheets.google.com/spreadsheet/embeddedform?bc%3Dtransparent%26f%3DArial%25252C%252BVerdana%25252C%252Bsans-serif%26hl%3Den_GB%26htc%3D%252523666666%26key%3D0AsXMMvBKGqckdDJsend5cW94SkVQeFRtSWVFVWh2blE%26lc%3D%252523336699%26pli%3D1%26tc%3D%252523333333%26ttl%3D0">Report Abuse</a>
      -
      <a href="http://www.google.com/accounts/TOS">Terms of Service</a>
      -
      <a href="http://www.google.com/google-d-s/terms.html">Additional Terms</a></small></span></div></div></div>
    </div>
  </div>
</div>

app/views/welcome/testimonial.html.erb
<div class="page-header text-center">
  <h1>Property Certify Testimonials<small> What our customers say about us</small></h1>
</div>
<div class="row">
	<div class="col-md-12">
		<%= testimonial('Super fast service, Certificate was emailed to us within a few hours! Wow! Thank you, would definitely recommend to others.', 'Denise H, Bromley') %>
	</div>
</div>

<div class="row">
	<div class="col-md-12">
		<%= testimonial('Excellent prompt service. I would have no hesitation in recommending Edward to any friends and colleagues', 'Wulston A, Wapping') %>
	</div>
</div>
<div class="row">
	<div class="col-md-12">
		<%= testimonial('The Energy Report was completed on time as scheduled by Mr Peck. On his visit to our property to compile the Certificate he was very courteous and considerate. We would not hesitate to recommend Property Certify and Mr Peck for a very efficient and thorough service. We would like to thank you very much for all your help.', 'Barbara P, Greenwich') %>
	</div>
</div>
<div class="row">
	<div class="col-md-12">
		<%= testimonial('Excellent service. A delight to deal with, very helpful, friendly and professional. Would highly recommend. Thank you.
', 'Sean J, Beckenham') %>
	</div>
</div>
<div class="row">
	<div class="col-md-12">
		<%= testimonial('Very speedy and professional service! Thanks', 'Rachel P, Bromley') %>
	</div>
</div>
<div class="row">
	<div class="col-md-12">
		<%= testimonial('Mitchel was very polite and friendly, even towards my 19 month old son. The inspection was done quickly and efficiently. A pleasure to deal with, thank you', 'Catherine M, Surrey Quays') %>
	</div>
</div>
<div class="row">
	<div class="col-md-12">
		<%= testimonial('Very pleased with the service received. Always here at the end of the phone to answer any queries we had. Would recommend Property Certify to family and friends.', 'Jane S, Lewisham') %>
	</div>
</div>
<div class="row">
	<div class="col-md-12">
		<%= testimonial('Very good service. We would recommend them and very reasonable also', 'Paul P, Bethnal Green') %>
	</div>
</div>
<div class="row">
	<div class="col-md-12">
		<%= testimonial('I didn\'t have an in depth knowledge of Inventories before i spoke to Edward but what surprised me after speaking with him was that he also did energy surveys. I decided to have one done on my letted Flat and i\'m glad i did. Edward turned up on time armed with his gadgets and a big smile. He explained everything that he was doing with his laser distance measuring device!. He advised me as he was carrying out the survey on why different materials within my house could or couldn\'t be made more energy efficient. He inspected the loft with his very impressive expendable ladder and explained that i could have new loft insulation put in that would be substantially part-funded by various grants.
The whole process took about 40 minutes and later that day i received an email from him with the fully energy report attached. It was very informative and has prompted me into action to make my house more energy efficient before the winter months arrive', 'Simon A, Dulwich') %>
	</div>
</div>